# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guii.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from LU_gui import Ui_Windowlu
from  cholesky_gui import Ui_Windowlt
from iter_gui import Ui_WindowGs

class Ui_MainWindow(object):

    def openWindow_lu(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Windowlu()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow_llt(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Windowlt()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow_iter(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_WindowGs()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(624, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-image: url(mathc.jpg);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 681, 91))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 8px 8px 8px;")
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
#         self.dgauss = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.openWindow_gd())
#         self.dgauss.setGeometry(QtCore.QRect(190, 200, 221, 51))
#         font = QtGui.QFont()
#         font.setFamily("Papyrus")
#         font.setPointSize(16)
#         self.dgauss.setFont(font)
#         self.dgauss.setStyleSheet("background-color:rgb(255, 255, 255);\n"
# "color:rgb(170, 85, 0);\n"
# "border-radius: 8px 8px 8px;")
#         self.dgauss.setObjectName("dgauss")
        self.lu = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.openWindow_lu())
        self.lu.setGeometry(QtCore.QRect(140, 160, 350, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(20)
        font.setBold(True)
        self.lu.setFont(font)
        self.lu.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(170, 85, 0);\n"
"border-radius: 8px 8px 8px;")
        self.lu.setObjectName("lu")
        self.cholesky = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.openWindow_llt())
        self.cholesky.setGeometry(QtCore.QRect(150, 275, 350, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(20)
        font.setBold(True)
        self.cholesky.setFont(font)
        self.cholesky.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(170, 85, 0);\n"
"border-radius: 8px 8px 8px;")
        self.cholesky.setObjectName("cholesky")

        self.iter = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.openWindow_iter())
        self.iter.setGeometry(QtCore.QRect(150, 390, 350, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.iter.setFont(font)
        self.iter.setStyleSheet("\n"
"color: rgb(170, 85, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px 8px 8px;")
        self.iter.setObjectName("iter")
#         self.directes = QtWidgets.QLabel(self.centralwidget)
#         self.directes.setGeometry(QtCore.QRect(140, 160, 331, 51))
#         font = QtGui.QFont()
#         font.setFamily("Papyrus")
#         font.setPointSize(25)
#         font.setBold(True)
#         font.setWeight(75)
#         self.directes.setFont(font)
#         self.directes.setStyleSheet("\n"
# "color: rgb(170, 85, 0);\n"
# "background-color: rgb(255, 255, 255);\n"
# "border-radius: 8px 8px 8px;")
#         self.directes.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
#         self.directes.setIndent(0)
#         self.directes.setObjectName("directes")
        self.by = QtWidgets.QLabel(self.centralwidget)
        self.by.setGeometry(QtCore.QRect(406, 580, 161, 20))
        self.by.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 italic 8pt \"Palatino Linotype\";")
        self.by.setIndent(0)
        self.by.setObjectName("by")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(9, 0))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "    Resolution des systemes  lineaires "))
        # self.dgauss.setText(_translate("MainWindow", "Methode de GAUSS"))
        self.lu.setText(_translate("MainWindow", "Methode LU (directe)"))
        self.cholesky.setText(_translate("MainWindow", "Methode LLt (directe)"))
        self.iter.setText(_translate("MainWindow", " Methodes iteratives"))
        self.by.setText(_translate("MainWindow", "     b64  QnkgRl9TQklMSQ=="))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
